- .env
Merge email functionality into main
> email functionality active

- app.py
- templates/update_ps_lead.html
> CRE call summmary to PS update 1

- app.py
- templates/update_lead.html
> PS remarks visibl to CRE update 2

- app.py
- requirements.txt
- templates/cre_dashboard.html
Ps remark update notification to CRE Dashboard
> Ps remark update notification to CRE Dashboard

- templates/update_ps_lead.html
> followup date not required if final status = lost

- app.py
- templates/ps_dashboard.html
> Leads not shifting through sections problem solved

- app.py
- templates/manage_leads.html
- templates/ps_call_attempt_history.html
- templates/ps_dashboard.html
- templates/update_ps_lead.html
> Ps call history feature added

- app.py
- templates/manage_leads.html
- templates/view_walkin_customers.html
added features to manage leas and lead journey
> Added features to manage leads and the lead journey

- app.py
- templates/manage_leads.html
> updated manage leads

- app.py
> ps updatte issue fixed

- app.py
- templates/analytics.html
> Adding Tables

- app.py
- templates/analytics.html
Adding Column in campaign analysis
> Adding Columns In Campaign Analysis

- templates/analytics.html
> Active CRE Count

- app.py
- templates/assign_leads.html
> Assign Leads Section

- app.py
> manage vehicle repair

- app.py
- templates/ps_dashboard.html
- templates/update_event_lead.html
Event leads update option for PS added
> Event leads update option for PS added

- app.py
- templates/cre_dashboard.html
- templates/update_event_lead_cre.html
added update button for CRE event leads
> added update button for CRE event leads

- app.py
- templates/update_event_lead.html
- templates/update_event_lead_cre.html
Sync Previous call summaries of event leads for PS and CRE's
> Sync Previous call summaries of event leads for PS and CRE's

- templates/cre_dashboard.html
> Sequence event leads

- templates/cre_dashboard.html
- templates/ps_dashboard.html
added and started the call attempt history buttons for both PS and CRE
> added and started the call attempt history buttons for both PS and CRE

- app.py
- templates/update_ps_lead.html
Fixed ps_dashboard bugs and walkin followups coming in today's follow up of PS.
> ps_dashboard bugs fixed.

- app.py
- templates/cre_dashboard.html
added number of calls  in fresh leads in front of lead status it will now show something like this 
RNR : 3
> added number of calls  in fresh leads in front of lead status

- templates/ps_dashboard.html
Hot Cold Warm Filters added in PS dashboards Pending Leads section
> Hot Cold Warm Filters added in PS dashboards Pending Leads section

- app.py
- templates/ps_dashboard.html
Added date range and todays filters for in PS dashboard
> Added date range and todays filters for in PS dashboard

- app.py
- templates/cre_dashboard.html
> notification issue solved

- app.py
- templates/cre_dashboard.html
- templates/cre_dashboard_leads_table.html
CRE called and other redirection problem solved
> CRE called and other redirection problem solved

- app.py
- templates/branch_head_dashboard.html
Fixed Branch Head Dashboard and Integration with ZOHO
> Fixed Branch Head Dashboard

- app.py
- templates/add_walkin_lead.html
- templates/rec_dashboard.html
Made a Reception Dashboard with all kpi and insigts required
> Reception Dashboard

- app.py
- templates/add_walkin_lead.html
- templates/rec_dashboard.html
- templates/update_walkin_lead.html
- templates/view_walkin_call_history.html
Call History and New KPI card added in rec_dashboard
> Reception Dashboard Improvements

- app.py
- deploy_optimizations.py
- optimized_lead_operations.py
added indexes for faster retrival
> added indexes for faster retrival

- templates/ps_dashboard.html
PS call attempt history started in pending leads PS Dashboard
> PS call attempt history started in pending leads PS Dashboard

- app.py
- templates/branch_head_dashboard.html
branch head all leads changes 2
> branch head all leads changes 2

- templates/update_event_lead_cre.html
- templates/update_lead.html
> Added out of Station option
